---
products:
- id: 469c7d34-8370-4f2d-876a-43a94b4c9868
  name: バスマジックリンつめかえ800
  amazon_url: https://www.amazon.co.jp/dp/B0GMPQL76Q
  yodobashi_url: https://www.yodobashi.com/product/100000001008044118/
- id: 9c83c809-6530-4a8b-b503-78cd2b8333ed
  name: クリーニング屋さんの襟エリそで潜洗剤
  amazon_url: https://www.amazon.co.jp/dp/B0CW6B49G2
  yodobashi_url: https://www.yodobashi.com/product/100000001009013257/
